### ISSUE TITLE
Subset by Spatial Extent - not working

### ISSUE THREAD

**Issue by jachope** [aodn/aodn-portal#2293] opened 2016-08-29 23:58 UTC
https://portal-systest.aodn.org.au
V4.25.5

Steps to reproduce
Add several collections (I added SRS Satellite - SST L3S - 06 day, ANFOG - delayed mode & Phytoplankton)
Draw a bounding box over the collections
Look at Step 3 for the filters added to the collections and look at download size

Also change the bounding box to other places and a box remains on the map for where previous bounding boxes were selected.
 

What I expected
Spatial extent to be applied to all collections (regardless of if it was bounding box or polygon)and to be displayed in Step 3 as part of the filtering

The download size should reduce when spatial subset applied

What happened
Spatial extent was not applied and did not display on step 3 and spatial subset remained very large (on one collection seen as 1.9GB before and then still 1.9GB after so not being applied) 

There are other Spatial extent issues loaded so it may be all related - #2283 and #2284

**Comment by pblain** [comment] 2016-08-30 03:05
#2288 _may_ also be related

**Comment by pmbohm** [comment] 2016-08-31 06:43
Not reproducible in current master. #2283 #2284 #2288 and this bug all were most likely caused by console errors occurring and stopping execution.

**Comment by jonescc** [comment] 2016-09-06 02:55
Note: for gridded data collections such as SRS the download file size will not reduce without changing the temporal extent as the download size is calculated from the unsubsetted netcdf file size.

Looks to be working OK for me in production - although phytoplankton size couldn't be estimated - no unsubsetted download option.   Do you have any details for collections for which this is not working?

**Comment by jonescc** [comment] 2016-09-06 03:37
Refer https://github.com/aodn/backlog/issues/26 - improving download estimation will be performed there.

**Comment by jonescc** [comment] 2016-09-06 06:06
Definitely a problem being able to draw two bounding boxes at once and missing spatial extent on step 3 - witness this happening on Kates browser.  Kate is still trying to work out steps to reproduce.  Also an issue with previous bounding box being left when a small bounding box drawn resulting in a feature info popup.

**Comment by bhasin85** [comment] 2016-09-15 23:43
@kereid is unable to reproduce it and suggested to close it.

**Closed by bhasin85** 2016-09-15 23:43 UTC
Labels: bug
