### ISSUE TITLE
Download error not informative

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2480] opened 2017-05-05 03:08 UTC
I know I've seen this error before but I can't find where or what it means.

Lesson learned - make systest the same as Production..... https://github.com/aodn/aodn-portal/issues/2467 

I set myself a reminder to check the collection mentioned in the above issue when Javaduck released to systest, so in good news I did get an email but bad news the message is not clear.

Steps to reproduce:

Add ANMN Temperature and Salinity TimeSeries, do not apply any subsets. Proceed to step 3 to download.

What should happen:

Either fails because it's too much data and the error tells you so, or it takes a while and succeeds, 

What does happen:

Fails and get error:
Process failed during execution org.postgresql.util.PSQLException: ERROR: syntax error at or near "null" Position: 214 ERROR: syntax error at or near "null" Position: 214

**Comment by julian1** [comment] 2017-05-29 23:08
Just to note, this is non-gridded and therefore netcdf generator and not gogo/javaduck

**Comment by julian1** [comment] 2017-05-29 23:10
Looks like it's generating badly formed sql, dropping in nulls in the join statement.
```
17-05-29 03:36:12 GMT 54.153.223.176 geoserver_wps_4_aws_syd harvest 16753 42601STATEMENT:  select * from (select ts_id as instance_id, * from anmn_ts.measurement) as data left join (select instrument_nominal_depth as "NOMINAL_DEPTH", * from anmn_ts.timeseries) instance on instance.id = data.instance_id null and data.instance_id = 15838 order by "TIME"
2017-05-29 03:36:12 GMT 54.153.223.176 geoserver_wps_4_aws_syd harvest 16753 25P02ERROR:  current transaction is aborted, commands ignored until end of transaction block
2017-05-29 03:36:12 GMT 54.153.223.176 geoserver_wps_4_aws_syd harvest 16753 25P02STATEMENT:  SELECT 1
```

**Comment by julian1** [comment] 2017-06-01 03:36
To reproduce against a local geoserver,
```
meteo@dell-work:~/imos/xxxx$ cat submit.sh 
#!/bin/bash

curl \
  --data @wps1.xml \
  --header "Content-Type: application/xml" \
  --header "Expect:" \
  'http://geoserver/geoserver/wps' | xmllint --format -

 
meteo@dell-work:~/imos/xxxx$ cat wps1.xml 
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<wps:Execute service="WPS" version="1.0.0" xmlns:wps="http://www.opengis.net/wps/1.0.0" xmlns:ows="http://www.opengis.net/ows/1.1" xmlns:ogc="http://www.opengis.net/ogc" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.o
rg/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/wps/1.0.0 http://schemas.opengis.net/wps/1.0.0/wpsExecute_request.xsd">

    <ows:Identifier>gs:NetcdfOutput</ows:Identifier>
    <wps:DataInputs>
        
            <wps:Input>
                <ows:Identifier>typeName</ows:Identifier>
                <wps:Data>
                    <wps:LiteralData>imos:anmn_ts_timeseries_data</wps:LiteralData>
                </wps:Data>
            </wps:Input>
        
            <wps:Input>
                <ows:Identifier>cqlFilter</ows:Identifier>
                <wps:Data>
                    <wps:LiteralData></wps:LiteralData>
                </wps:Data>
            </wps:Input>
        
        <wps:Input>
            <ows:Identifier>callbackUrl</ows:Identifier>
            <wps:Data>
                <wps:LiteralData>
                    https://portal.aodn.org.au/wps/jobComplete
                </wps:LiteralData>
            </wps:Data>
        </wps:Input>
        <wps:Input>
            <ows:Identifier>callbackParams</ows:Identifier>
            <wps:Data>
                <wps:LiteralData>email.to=jfca@utas.edu.au</wps:LiteralData>
            </wps:Data>
        </wps:Input>
    </wps:DataInputs>
    <wps:ResponseForm>
        <wps:ResponseDocument storeExecuteResponse="true" status="true">
            <wps:Output asReference="true" mimeType="application/zip">
                <ows:Identifier>result</ows:Identifier>
            </wps:Output>
        </wps:ResponseDocument>
    </wps:ResponseForm>
</wps:Execute>
```

**Comment by julian1** [comment] 2017-06-01 04:39
I think it's unrelated. But the initial query appears to be very expensive,

```
harvest=# explain  select distinct data.instance_id from (select ts_id as instance_id, * from anmn_ts.measurement) as data left join (select instrument_nominal_depth as "NOMINAL_DEPTH", * from anmn_ts.timeseries) instance on instance.id = data.instance_id  ;
-[ RECORD 1 ]-----------------------------------------------------------------------------
QUERY PLAN | HashAggregate  (cost=8927392.80..8927434.34 rows=4154 width=8)
-[ RECORD 2 ]-----------------------------------------------------------------------------
QUERY PLAN |   Group Key: measurement.ts_id
-[ RECORD 3 ]-----------------------------------------------------------------------------
QUERY PLAN |   ->  Seq Scan on measurement  (cost=0.00..7933255.84 rows=397654784 width=8)
```

**Comment by julian1** [comment] 2017-06-01 04:43
```
harvest=# select count(1) from anmn_ts.measurement 
harvest-# ;
^[[2;5~-[ RECORD 1 ]----
count | 397655621
```

A sequential scan on 400 million rows.

**Comment by julian1** [comment] 2017-06-01 04:51
So it looks like the initial query is valid sql, albeit it runs very slow. However it fails when the instance sql is bad,

```
...  data.instance_id null and data.instance_id = 15838  ...
```

**Comment by julian1** [comment] 2017-06-01 05:08
It appears there's a heavy load on the db. not sure what it's from.

**Comment by julian1** [comment] 2017-06-01 05:37
Looks like upstream repo is down, so I can't compile it.

```
$ mvn clean install -Dmaven.test.skip=true
[INFO] Scanning for projects...
Downloading: http://repo.boundlessgeo.com/main/org/geoserver/geoserver/2.8.4-IMOS-SNAPSHOT/maven-metadata.xml


^Cmeteo@dell-work:~/imos/geoserver-build$ wget http://repo.boundlessgeo.com
--2017-06-01 15:35:48--  http://repo.boundlessgeo.com/
Resolving repo.boundlessgeo.com (repo.boundlessgeo.com)... 52.22.156.115
Connecting to repo.boundlessgeo.com (repo.boundlessgeo.com)|52.22.156.115|:80... ^[[2;5~
```

remind me why we deleted archiva?

**Comment by julian1** [comment] 2017-06-01 06:30
After fixing the sql generation, it's still trying to perform an expensive sequential scan. The join constraint requires a specific instance id and a subsequent sort ordering, so I suspect there's something quite wrong with the indexes.

```
harvest=# explain select * from (select ts_id as instance_id, * from anmn_ts.measurement) as data left join (select instrument_nominal_depth as "NOMINAL_DEPTH", * from anmn_ts.timeseries) instance on instance.id = data.instance_id and data.instance_id = 15838 order by "TIME";
-[ RECORD 1 ]------------------------------------------------------------------------------------
QUERY PLAN | Sort  (cost=909828331.78..910822468.74 rows=397654784 width=949)
-[ RECORD 2 ]------------------------------------------------------------------------------------
QUERY PLAN |   Sort Key: measurement."TIME"
-[ RECORD 3 ]------------------------------------------------------------------------------------
QUERY PLAN |   ->  Hash Left Join  (cost=1442.41..23934727.45 rows=397654784 width=949)
-[ RECORD 4 ]------------------------------------------------------------------------------------
QUERY PLAN |         Hash Cond: (measurement.ts_id = timeseries.id)
-[ RECORD 5 ]------------------------------------------------------------------------------------
QUERY PLAN |         Join Filter: (measurement.ts_id = 15838)
-[ RECORD 6 ]------------------------------------------------------------------------------------
QUERY PLAN |         ->  Seq Scan on measurement  (cost=0.00..7933255.84 rows=397654784 width=62)
-[ RECORD 7 ]------------------------------------------------------------------------------------
QUERY PLAN |         ->  Hash  (cost=735.07..735.07 rows=5707 width=887)
-[ RECORD 8 ]------------------------------------------------------------------------------------
QUERY PLAN |               ->  Seq Scan on timeseries  (cost=0.00..735.07 rows=5707 width=887)
```

**Comment by julian1** [comment] 2017-06-01 06:33
There's an aggregate index over ts_id and index. It might be better with a single one on ts_id, since this looks like the one that is used to join with the measurement table.

```
\d: extra argument ";" ignored
harvest=# \d anmn_ts.measurement  ;
                   Table "anmn_ts.measurement"
          Column          |           Type           | Modifiers 
--------------------------+--------------------------+-----------
 ts_id                    | bigint                   | not null
 index                    | bigint                   | not null
 TIME                     | timestamp with time zone | not null
 TIME_quality_control     | character(1)             | 
 DEPTH                    | real                     | 
 DEPTH_quality_control    | character(1)             | 
 TEMP                     | real                     | 
 TEMP_quality_control     | character(1)             | 
 CNDC                     | real                     | 
 CNDC_quality_control     | character(1)             | 
 PSAL                     | real                     | 
 PSAL_quality_control     | character(1)             | 
 PRES                     | real                     | 
 PRES_quality_control     | character(1)             | 
 PRES_REL                 | real                     | 
 PRES_REL_quality_control | character(1)             | 
Indexes:
    "measurement_fk" PRIMARY KEY, btree (ts_id, index)
    "timeseries_time_idx" btree ("TIME")
```

**Comment by julian1** [comment] 2017-06-01 06:38
To note, it's been sitting there for 20 minutes, still trying to get the data for the first instance.

**Comment by jonescc** [comment] 2017-06-01 22:27
Changing to an inner join:

```
explain select *
  from (select ts_id as instance_id, * from anmn_ts.measurement) as data
  join (select instrument_nominal_depth as "NOMINAL_DEPTH", * from anmn_ts.timeseries) instance on instance.id = data.instance_id and data.instance_id = 15838
order by "TIME";

"Sort  (cost=320573.75..320772.51 rows=79505 width=949)"
"  Sort Key: measurement."TIME""
"  ->  Nested Loop  (cost=0.85..280947.04 rows=79505 width=949)"
"        ->  Index Scan using timeseries_pk on timeseries  (cost=0.28..8.30 rows=1 width=887)"
"              Index Cond: (id = 15838)"
"        ->  Index Scan using measurement_fk on measurement  (cost=0.57..280143.69 rows=79505 width=62)"
"              Index Cond: (ts_id = 15838)"
```

Or using timeseries to limit to instance instead of measurement:

```
explain select *
 from (select ts_id as instance_id, * from anmn_ts.measurement) as data
 left join (select instrument_nominal_depth as "NOMINAL_DEPTH", * from anmn_ts.timeseries) instance on instance.id = data.instance_id and instance.id = 15838
 order by "TIME";

"Nested Loop Left Join  (cost=0.85..767230510.89 rows=397655616 width=949)"
"  Join Filter: (timeseries.id = measurement.ts_id)"
"  ->  Index Scan using timeseries_time_idx on measurement  (cost=0.57..761265668.35 rows=397655616 width=62)"
"  ->  Materialize  (cost=0.28..8.31 rows=1 width=887)"
"        ->  Index Scan using timeseries_pk on timeseries  (cost=0.28..8.30 rows=1 width=887)"
"              Index Cond: (id = 15838)"
```

Left join stops postgres from optimising the query by forcing filtering on data first.  Just filtering on the instances first is better and doesn't require the left join to be dropped (although better if it can be because it stops postgres from optimising the join order for optimal performance)

**Comment by jonescc** [comment] 2017-06-01 22:48
https://www.postgresql.org/docs/9.1/static/explicit-joins.html

**Comment by julian1** [comment] 2017-06-02 00:30
The template sql blows the GC heap.

```
01 Jun 16:15:42 INFO [ncdfgenerator.NcdfEncoder] - instanceId 15838, select * from (select ts_id as instance_id, * from anmn_ts.measurement) as data left join (select instrument_nominal_depth as "NOMINAL_DEPTH", * from anmn_ts.timeseries) instance on instance.id = data.instance_id and data.instance_id = 15838 order by "TIME";
java.lang.OutOfMemoryError: GC overhead limit exceeded
Dumping heap to java_pid19232.hprof ...
Heap dump file created [5212568684 bytes in 212.278 secs]
01 Jun 17:05:50 WARN [ncdfgenerator.NcdfEncoder] - Problem closing org.apache.tomcat.dbcp.dbcp.PoolingDataSource.PoolGuardConnectionWrapper
```

**Comment by julian1** [comment] 2017-06-04 23:49
Not sure that I can fix this in the time remaining to me, and given that the code has changed substantially since it was first written. I agree with @jonescc observations that the joins should be inner-joins. There appear to be multiple cases where sql generation can return empty syntax, and those cases are not being catered too, leading to 'null' errors in the output log.

I've pushed the work to date to this branch, https://github.com/aodn/geoserver-build/compare/fix-2480?expand=1

The changes affect fundamental encoding properties. When/if this gets fixed, it probably needs project officers to review and test the generated netcdfs as well as the reinstatement of integration tests.

**Comment by julian1** [comment] 2017-06-05 01:47
@pblain @smancini @bpasquer 

Benedicte asked me about what she needs to do to create new netcdf layers for anfog_dm.

Ideally, the issues with this service could be resolved before effort is invested making content changes. The layer development workflow using the wps service in geoserver is substantially different to what it was in the past, so guidance is also needed (I wasn't involved in these changes, so don't know myself). It might make sense to review the timeline for the aws batch implementation because that could change the implementation as well (eg. the cql filter code).

**Comment by pblain** [comment] 2017-06-20 03:14
Discussed at scrum planning - closing

**Closed by pblain** 2017-06-20 03:14 UTC
Labels: bug
