### ISSUE TITLE
Text search label not user intuitive

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#1978] opened 2015-09-16 04:36 UTC
App version: 4.14.0
            Build date: Tue Sep 15 12:12:50 AEST 2015
            Build number: 16
            Git ref: 46c86164f7408e5001457edf483241bad348f0a9
        -->

Steps to reproduce:

On step one find the text search facet.

What should happen:

Reads "Free text search" or even just "Text search"

What does happen:

Reads "Keyword"

@atkinsn has provided feedback that the previous labeling is more intuitive and more accurately reflects what the user is going to select that facet for. Labeling keywords seems to suggest that the text search would just be occuring within the keywords section of the metadata record (and this is indeed what such a labelled feature in the MEST is designed to do)  and labelling it this way will make this feature less "attractive" to users, and could lead to confusion. 

It could also be interpreted by a user that this is just another pre-filled drop-down list and not actually a manual search for anything they want to look for.

**Comment by pmbohm** [comment] 2015-09-16 07:00
@pblain instructed me to make this change so that it "will make this feature less attractive to users".
As the free text search feature does not really work as well as intended at this stage, the feature is given less prominence as a design decision.

**Comment by pblain** [comment] 2015-09-21 07:01
Well I'm not sure the reason I gave was to make it less attractive to users. I might have said that I don't want to draw too much attention to it until we are confident in it. The problem with this search is that it's primitive.  All this feature does is search some or all of the metadata - which makes it a "keyword" search.   A "full text" search goes beyond just the metadata and searches documents, database, or whatever. A "free text" search is less well defined but implies, to me at least, that it is a google style intelligent search. Our search is definitely not that!
Users should be familiar with keyword searches if they have used other websites - dare I say it - like carsales :-)
![image](https://cloud.githubusercontent.com/assets/2802359/9986616/28cc49fc-6082-11e5-8de2-c03735fa65ec.png)

**Comment by pblain** [comment] 2015-09-21 07:05
@pmbohm @kereid @atkinsn Closing for the reasons above

**Closed by pblain** 2015-09-21 07:05 UTC
Labels: enhancement
