### ISSUE TITLE
Some layers with diver platform have empty platform row in results

### ISSUE THREAD

**Issue by akashisama** [aodn/aodn-portal#2502] opened 2017-06-21 02:02 UTC
**Steps to reproduce:**

In the platform facet expand "Biological platform" and select "diver".

**What should happen:**

All results contain "Biological platform" in the platform row.

**What does happen:**

"Mapping of selected areas of Cockburn Sound, Western Australia", "Habitat Maps derived from Point Lookout Ecological Surveys (PLEA)" and "Ecophysiology of three habitat-forming seaweeds across a depth and latitudinal gradient in southeastern Australia" are missing the platform row.

**Comment by kereid** [comment] 2017-06-21 04:35
Had a chat to Nat and might possibly have something to do with the Metadata containing a short name and the portal not handling but that's just a guess otherwise not sure why.

**Comment by eflukes** [comment] 2017-06-21 05:26
?Just saw this pop up - I've checked out both those layers as they're both coming from us (IMAS).


For this layer: "Ecophysiology of three habitat-forming seaweeds across a depth and latitudinal gradient in southeastern Australia?", I couldn't reproduce the issue described. Biological platform is showing as expected - please let me know if I've missed something.


The other two layers (Cockburn Sound, Point Lookout) are now functioning as expected in the IMAS Data Portal, and should be fixed in the AODN Portal on next harvest. Initially I thought the issue occurred because both layers have multiple instances of the same data parameter ("Biotic taxonomic identification" for Cockburn Sound, "Benthic physical habitat" (freetext) for Point Lookout) collected using different platforms, but actually that's not the case. The missing platform row was because the portal only displays a single platform result at Step 1.


For example: if a layer contains "Temperature of the water body" collected by a research vessel as Data Parameter #1 and "Abundance of biota" collected by a diver as Data Parameter #2, only the first chronological instance of a platform ("research vessel") is displayed.? In this case, the first instance of a data parameter was not associated with a platform from the controlled vocabulary, so the portal returned a blank row. I've worked around this by re-ordering the data parameters in these two records.

The issue becomes more complicated again if a single data parameter is collected using multiple different platforms. e.g. for "Mapping of selected areas of Cockburn Sound, Western Australia", the data parameter "Biotic taxonomic identification" was collected in 4 different ways, using 3 different platforms (aerial photographs from light aircraft, underwater cameras from research vessel, sidescan sonar from research vessel, transects by divers). Each of those 4 methods, and 3 platforms, was used to measure a single parameter - ie taxonomic identification of seagrass species. However, only the first platform is displayed at Step 1, so you're potentially missing out on displaying useful information. Moreover, if the platform doesn't currently exist in the AODN Platform vocab, suddenly the ordering of data parameters in the metadata influences how the record displays in the Portal (which is possibly not intentional).

It's totally up to you guys if you want to raise this as a bug or feature request - just thought I'd let you know :-)




________________________________
Dr EMMA FLUKES
NESP MBH Data Manager | IMAS Research Data Analyst

NESP Marine Biodiversity Hub | Institute for Marine and Antarctic Studies (IMAS)
University of Tasmania
Office: IMAS Waterfront Building (113.21), 20 Castray Espl, Battery Point
Mail: University of Tasmania, Private Bag 129, HOBART TAS 7001
M +61408 901 952
www.nespmarine.edu.au | www.imas.utas.edu.au

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
IMAS - in partnership with the Tasmanian State Government
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
________________________________

**Comment by atkinsn** [comment] 2017-06-21 05:52
Thanks @eflukes for the excellent investigation

**Comment by akashisama** [comment] 2017-06-21 06:37
Oh wow, that was fast. Looks like I must have been going crazy with that third layer.

**Comment by kereid** [comment] 2017-06-21 23:17
Bug notes - platform should be discoverable from metadata regardless of preceeding empty platform elements, 
OR
platform should be discoverable from metadata regardless of preceeding non-vocab element i.e. just text

**Comment by kereid** [comment] 2017-06-21 23:18
Thanks @eflukes. Nat and I have discussed and come up with the following:

This bug will remain open see above comment.

We have opened a backlog item https://github.com/aodn/backlog/issues/648 to cover showing multiple plaforms on step 1 of the portal.

Regarding new platform entries they need to be submitted to Nat to enter into the AODN vocab otherwise they aren't recognised in the facets, so please supply a list of current missing terms.

**Comment by kereid** [comment] 2017-06-28 05:23
Not sure why I got assigned I can't fix a portal bug.

**Comment by pblain** [comment] 2017-06-29 01:47
@kereid - feel free to close it. There's a backlog item for it right? Or is there some other reason to keep it open?

**Comment by kereid** [comment] 2017-06-29 02:12
It is a bug that needs to be fixed. The backlog is a different issue (a feature request) that was discovered through the reporting of the bug.

**Comment by pblain** [comment] 2017-06-29 04:39
@kereid (and @akashisama ) - OK so you're referring to this : https://github.com/aodn/aodn-portal/issues/2502#issuecomment-310231407. Is this correct? It might be worth writing a new bug description below so it's a bit clearer to the person who picks this up. I say this because the "steps to reproduce" no longer result in the issue. You can also assign it to me.

**Comment by kereid** [comment] 2017-06-29 05:23
@pblain, ah right with you now, yes it's fixed in production because Emma manually fixed the records that we found the issue on. 


@atkinsn  has created a test record in RC to demonstrate http://portal-rc.aodn.org.au/search?uuid=fedd2f8d-03f1-45a2-b48d-13b015fa7839

Steps to reproduce:

In the platform facet expand "biological platform" and select "diver"

What should happen:

The result contains "biological platform" in the platform row

What does happen:

Collection is missing the row, because the portal only looks at the first platform in the metadata and if it is not valid does not continue on to find the next valid one

**Closed** 2017-07-06 03:46 UTC
Labels: bug
