### ISSUE TITLE
Accordion - multiple items open at same time

### ISSUE THREAD

**Issue by dnahodil** [aodn/aodn-portal#1823] opened 2015-07-03 04:44 UTC
**Steps to reproduce**
Quickly multi select 3 or 4 layers on step one - going to step 2 and then going back to step 1 multi-selecting a few more layers and going to step 2 again.  Sometimes two or more accordion panels will then be expanded.

**What does happen**
You can end up with multiple items open in the accordion

**What should happen**
Only the last-added item should be open

**Comment by pmbohm** [comment] 2015-07-15 05:59
Craig researched this:
"What's happening here is Ext records whether a panel is collapsed or not using a collapsed property on the panel.  It won't collapse the panel if this property is set to true.   The problem here is that Ext doesn't change the collapsed property to false until the expand panel animation is complete.   This doesn't work well with Ext.ux.NonCollapsingAccordionLayout.  Refer to the beforeExpandPanel handler added to each panel by this component:
```
    beforeExpandPanel : function(panel) {
        var panelToCollapse = this.currentlyExpandedPanel;  // A holder for the previously selected panel
        this.currentlyExpandedPanel = panel;                // Set the new panel as the currently expanded one
        panelToCollapse.collapse();                         // Collapse the previously selected panel
        return true;
    },
```

When expanding the new panel, this code tries to collapse the previous one, but Ext won't collapse the panel if the panel is still being expanded.  And so if you try to expand two panels in quick succession, the first may not actually get collapsed when expanding the second if the first is still expanding."

**Comment by kereid** [comment] 2015-07-23 02:06
@dnahodil should this be fixed in my current round of testing?

**Comment by dnahodil** [comment] 2015-07-23 02:13
Yeah, should be. Are you still seeing it?

**Comment by kereid** [comment] 2015-07-23 02:15
reopening as @dnahodil confirmed occurrence on my machine.

**Comment by jonescc** [comment] 2015-08-14 10:02
Couldn't reproduce this on my laptop no matter how much I tried.  Need to watch @kereid do this to see how she gets it to happen.

**Comment by kereid** [comment] 2015-08-17 04:00
@jonescc  On production if you add the first the collections individually (not ctrl click) and on the third stay on step 2 until it's loaded then go back to step one and add the next 3 collections via ctrl click it should happen 

On systest add the first 7 collections using ctrl click then click to go onto step 2, go back to stap 1 and add the next 2 collections using ctrl click then click to go to step 2

**Comment by kereid** [comment] 2015-09-03 22:23
Still seeing this intermittently 

App version: 4.12.1
            Build date: Tue Sep 01 15:30:10 AEST 2015
            Build number: 14
            Git ref: d6c409ad34d5a579c4508c81a0767f7f285fef3e
        -->

![2open](https://cloud.githubusercontent.com/assets/2906602/9672385/7c84ad26-52dd-11e5-998d-7f43005e7fad.jpg)

To reproduce:

Select Satellite Platform. Add the first 5 collections via control click then add the 6th then 7th but 7th don't hold down ctrl.

**Comment by pmbohm** [comment] 2015-09-07 00:41
@pblain I'm going to suggest that this is as far as we should go trying to plug this bug for the reasons stated in https://github.com/aodn/aodn-portal/pull/1914

Its been looked at numerous times. The source of the problem is behaviour we want that isnt' provided by Ext which we then have then tried to override. I think that the bug will occur for a few people for a small percentage of the time and is not a deal breaker.  One thing will fix it - a new JS framework

**Comment by pblain** [comment] 2015-09-07 01:28
@pmbohm - OK I'll close as wont fix.  As I understand it, this only happens when you use the ctrl-click - which  the average user wouldn't be aware of.  We can add tracking of ctrl-click to GA at some point to track usage.

**Closed by pblain** 2015-09-07 01:28 UTC
Labels: bug
