### ISSUE TITLE
Map disappears

### ISSUE THREAD

**Issue by pblain** [aodn/aodn-portal#1730] opened 2015-04-21 05:12 UTC
Chrome: Version 41.0.2272.101

Steps to reproduce:
1. Step 1: Add a data collection
2. Step 2: Create a subset (anything - doesn't matter)
3. Step 3: Download the subset (or something else).  The important thing is that the download bar appears at the bottom of chrome (showing the file name)
4. Go back to Step 2
5. It may also be necessary to click the X at the far right of the download bar (to close the bar)

What should happen:
1. Not much. 

What does happen:
1. The map disappears

![image](https://cloud.githubusercontent.com/assets/2802359/7245653/3d3e2978-e832-11e4-96e4-bf7ce832157a.png)

**Comment by anguss00** [comment] 2015-04-21 06:32
Also present in version 42.0.2311.90, but need to close the download bar

**Comment by danfruehauf** [comment] 2015-04-24 01:58
Maybe we should update OpenLayers?

**Comment by anguss00** [comment] 2015-04-24 04:22
Could be a good idea. I've investigated this issue and it is a bug between OpenLayers and google chrome. See https://github.com/openlayers/openlayers/issues/1181 and https://github.com/openlayers/openlayers/issues/1207. The issue is caused (I think) by the window resizing that occurs when the download bar is removed in Chrome. The workaround suggested is adding the following to CSS: 

svg {
-webkit-transform: none !important;
}
.olTileImage {
-webkit-backface-visibility: visible !important;
-webkit-transform: none !important;
}

**Comment by danfruehauf** [comment] 2015-04-24 04:30
As much as this will probably fix it, I think that can also be a good reason to investigate an upgrade of OpenLayers. We're a major version behind after all.

**Comment by anguss00** [comment] 2015-04-24 04:33
Yep, I'd agree with that for sure. I'd prefer to update rather than introduce a hacky fix.

**Comment by danfruehauf** [comment] 2015-04-24 04:38
Lets just note that this may actually be "more than a bug" in our definition. Can get quite involved.

**Comment by anguss00** [comment] 2015-04-24 04:39
Yeah, agreed. If we want to fix this properly it's more than a bug

**Comment by anguss00** [comment] 2015-04-28 07:16
Ok, @dnahodil and I have looked at this further (including the upgrade). The upgrade process is more involved than a simple replace (and there is virtually no documentation available. Notably, in the comments in https://github.com/openlayers/openlayers/issues/1181 users who are on 2.13.1 are still reporting the issue (although some users have had success by forcing refreshes on tile resize). The upshot is, we would have to upgrade to 2.13.1 (as the refresh fix does not work with 2.10) and then apply the fix, hoping that it then works. What do you think @pblain? I think that this is going to get a lot bigger than a bug fix at the moment.

**Comment by danfruehauf** [comment] 2015-05-20 03:03
Closed by #1754

**Closed by danfruehauf** 2015-05-20 03:03 UTC
Labels: bug
