### ISSUE TITLE
Time selection shifting a month after typing

### ISSUE THREAD

**Issue by ocehugo** [aodn/aodn-portal#2683] opened 2018-07-31 03:38 UTC
Reproduction:
```
1. Step-1 search for ```radar delayed capricorn velocity```
2. Select/go step 2
3. The date box "From" says 2007-10-15 23:30 UTC.
4. Select the date box "From" and type 2013-02-01.
5. Press tab or click outside/any other area in the page.
6. The date is shift by a month to 2013-03-01. 
```

What I would expect:
No shift or #2680 when implemented.

**Comment by ggalibert** [comment] 2018-07-31 04:42
Also, worth noting that on second attempt the date is not jumping +1 month any more, yet the display is still stuck on the former date. The only way to update the display is to then select an hour but then the month jumps +1 again!

**Comment by pblain** [comment] 2018-08-14 04:26
Duplicate of #2685

**Closed by pblain** 2018-08-14 04:26 UTC
Labels: bug, duplicate
