### ISSUE TITLE
Bounding box filter on step 1 not bringing all the collections

### ISSUE THREAD

**Issue by evacougnon** [aodn/aodn-portal#2956] opened 2023-04-03 04:04 UTC
This issue tracker is only for AODN Portal issues.

### Steps to reproduce the issue
1. Step 1 of Portal systest https://portal-systest.aodn.org.au/search
2. Expend the "Geographic Boundary" filter
3. Selected a bounding box just off Davis station in Antarctica (est of the Amery ice shelf, or south est of the Kerguelen plateau -- see screenshot below)

### Expected behaviour
List all the collections with data matching the bounding box selected in the filters

### Actual behaviour
The results give at least 3 collections without data for the selected area:
- IMOS - SOOP-Sea Surface Temperature (SST) Sub-facility - Near real-time data ; even the spatial extend shown on step 1 doesn't show anything in this area
- CSIRO O&A RV Investigator XBT Data Overview (2014 onwards) ; spatial extend on step 1 indicates there might be something but no data available in this area in step 2
- CSIRO O&A Current Meter Mooring Data Overview (1983 - 1998)  ; spatial extend on step 1 indicates there might be something but no data available in this area in step 2
At least one collection missing:
- IMOS - Animal Tracking Facility - Satellite Relay Tagging Program - Near real-time data with quality-controlled locations -- potentially linked to https://github.com/aodn/PO-Backlog/issues/3432 but weird it only impacts the NRT collection while the DM looks fine and they're both using teh same harvester

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.
![Screenshot from 2023-03-30 15-08-05](https://user-images.githubusercontent.com/5467402/229408572-ab3baf97-00b4-4317-8d77-e5c4b1e6bc95.png)

### What version of the aodn portal are you using?
4.42.102

### Which browser are you using?
Chrome

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.
Associated test: https://aodn.testrail.com/index.php?/tests/view/84329

## DOD @vietnguyengit

**Comment by Chetnamann** [comment] 2023-05-25 03:53
same issue 

What version of the aodn portal are you using?
4.42.104

Which browser are you using?
Chrome

**Comment by vfisaac** [comment] 2023-07-12 05:59
Feedback from Nat - these 2 external collections can be ignored due to the spatial extent in their metadata records
- CSIRO O&A RV Investigator XBT Data Overview (2014 onwards) 
- CSIRO O&A Current Meter Mooring Data Overview (1983 - 1998) 
![image](https://github.com/aodn/aodn-portal/assets/110369193/9916b0e1-843c-49f4-90cf-b9e4886d3c6f)

**Comment by atkinsn** [comment] 2023-07-12 06:02
The issue with the SOOP SST collection, is that for some reason Geonetwork is combining all the spatial extents into 1 bounding box, hence the false results.
![image](https://github.com/aodn/aodn-portal/assets/4187605/20415b21-0091-4519-b6ff-bf542d2a7098)

Contrast with another collection which is maintaining its accurate spatial extents in Geonetwork full view
IMOS - SOOP Expendable Bathythermographs (XBT) Research Group - XBT real-time data 
![image](https://github.com/aodn/aodn-portal/assets/4187605/6e508f45-3b9b-4b75-b8ee-f433608ce5ad)

**Comment by utas-raymondng** [comment] 2023-07-14 07:32
Side note, if you click the more button, it seems point to the wrong page? [more](https://marlin.csiro.au/geonetwork/srv/eng/catalog.search#/metadata/d5a640e7-c695-23e1-e043-08114f8c7b58)



![Image](https://github.com/aodn/aodn-portal/assets/101624355/89fa674e-9e6e-479c-985d-ddff4afc654a)

**Comment by atkinsn** [comment] 2023-07-17 02:06
> Side note, if you click the more button, it seems point to the wrong page? [more](https://marlin.csiro.au/geonetwork/srv/eng/catalog.search#/metadata/d5a640e7-c695-23e1-e043-08114f8c7b58)
> 
> ![Image](https://user-images.githubusercontent.com/101624355/253503886-89fa674e-9e6e-479c-985d-ddff4afc654a.png)

Weird - its the right metadata record, as the title is correct, however the Point of truth URL points to one of its sister records (also in the Portal). I will delete it, and re-harvest.

**Comment by atkinsn** [comment] 2023-07-17 02:52
CSIRO have the wrong point of truth URL on this record, I will reach out to them to amend

**Comment by atkinsn** [comment] 2023-07-18 05:36
CSIRO have fixed it :)

**Comment by utas-raymondng** [comment] 2023-08-15 00:23
# investigation notes on how to repeat the case:

## How to re-produce
1. You run a genetwork instance on your local PC. https://github.com/aodn/geonetwork-build
2. Export the XML from catalogue-imos or other geonetwork of this UUID ca15915b-38c5-4e95-8d25-9cc42c4dd485, attached file [catalog-imos.zip](https://github.com/aodn/aodn-portal/files/12340334/catalog-imos.zip)
3. Run this [url](http://localhost:8080/geonetwork/srv/eng/xml.search?geometry=POLYGON((87.890625%20-61.48046875%2C97.20703125%20-61.83203125%2C95.44921875%20-67.984375%2C90.17578125%20-67.10546875%2C87.890625%20-61.48046875))&fast=index)
4. You see this appear in the output XML
```XML
<geonet:info xmlns:geonet="http://www.fao.org/geonetwork">
<id>130</id>
<uuid>ca15915b-38c5-4e95-8d25-9cc42c4dd485</uuid>
<schema>iso19115-3.2018</schema>
<createDate>2023-08-11T16:20:54</createDate>
<changeDate>2023-08-14T15:39:01</changeDate>
<source>54f007c1-9245-41ff-839e-dfc1980275b5</source>
<isPublishedToAll>true</isPublishedToAll>
<view>true</view>
<notify>false</notify>
<download>true</download>
<dynamic>true</dynamic>
<featured>false</featured>
<selected>false</selected>
<category internal="true">dataset</category>
</geonet:info>
```
Which is not expected

## Why geonetwork return this
I have no idea at the moment, the problem goes down to this particular class, so if you set a break point to this line for class org.locationtech.jts.geom.Envelope method 

    public boolean intersects(Envelope other) {
        if (!this.isNull() && !other.isNull()) {
            return !(other.minx > this.maxx) && !(other.maxx < this.minx) && !(other.miny > this.maxy) && !(other.maxy < this.miny);
        } else {
            return false;
        }
    }

The first return line return true for some of the bounding box area namely 
(a) Env[minx = 87.890625 : maxx = 97.20703125, miny = -67.984375 : maxy = -61.48046875], matches this (b) Env[minx = -180, maxx = 180, min y = -70, ,maxy = 50]. Where (b) comes I have no clue. (a) comes from the request link query parameter geometory=POLYGON((87.890625 -61.48046875,97.20703125 -61.83203125,95.44921875 -67.984375,90.17578125 -67.10546875,87.890625 -61.48046875))


The geonetwork in this case use relation = overlaps_bbox class to do the compare. (OverlapsBBoxFilter.class)

The calling class is SearchManager.class and there it provision the filter class 
```java
types.put("encloses".toLowerCase(), SearchManager.constructor(ContainsFilter.class));
types.put("crosses".toLowerCase(), SearchManager.constructor(CrossesFilter.class));
types.put("fullyOutsideOf".toLowerCase(), SearchManager.constructor(IsFullyOutsideOfFilter.class));
types.put("equal".toLowerCase(), SearchManager.constructor(EqualsFilter.class));
types.put("intersection".toLowerCase(), SearchManager.constructor(IntersectionFilter.class));
types.put("overlaps".toLowerCase(), SearchManager.constructor(OverlapsFilter.class));
types.put("touches".toLowerCase(), SearchManager.constructor(TouchesFilter.class));
types.put("within_bbox".toLowerCase(), SearchManager.constructor(WithinBBoxFilter.class));
types.put("overlaps_bbox".toLowerCase(), SearchManager.constructor(OverlapsBBoxFilter.class));
```

and the filter happens in this method, and finally call intersects in the Environment -> intersects()

```java
public SpatialFilter filter(Query query, int numHits, Collection<Geometry> geom, Element request) throws Exception {
            this._lock.lock();

            SpatialFilter var6;
            try {
                String relation = Util.getParam(request, "relation", "intersection");
                if (geom.size() != 1) {
                    Collection<SpatialFilter> filters = new ArrayList(geom.size());
                    Envelope bounds = null;

                    Geometry geometry;
                    for(Iterator var8 = geom.iterator(); var8.hasNext(); filters.add(((Constructor)this._types.get(relation)).newInstance(query, numHits, geometry, new SearchManager.Spatial.SpatialIndexAccessor()))) {
                        geometry = (Geometry)var8.next();
                        if (bounds == null) {
                            bounds = geometry.getEnvelopeInternal();
                        } else {
                            bounds.expandToInclude(geometry.getEnvelopeInternal());
                        }
                    }
```

**Comment by utas-raymondng** [comment] 2023-08-17 05:45
@ggalibert mentioned that it maybe a low priority task given portal on demise path.

**Comment by vfisaac** [comment] 2024-09-20 06:03
Confirmed with @bpasquer this does not need to be resolved. Closing

**Closed as completed by vfisaac** 2024-09-20 06:03 UTC
Labels: bug
