### ISSUE TITLE
No filter options should hide the filter

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#1849] opened 2015-07-23 22:37 UTC
App version: 4.9.0
            Build date: Fri Jul 17 13:45:28 AEST 2015
            Build number: 7
            Git ref: 182b0ac883c8e8b926cee97a6be95f88ac0c1338
        -->

Steps to reproduce:

Add Argo to map, on step 2 try to select platform number or project name

What should happen:

Can either pick from a list or don't see filter header at all

What does happen:

Can see that the filter headers are there but the drop-down arrow is inactive and box reads "No options available"

**Comment by dnahodil** [comment] 2015-07-28 04:16
Before we address this issue (e.g. by hiding the controls if there are no options) we need to find out how often this is happening and why. Basically, there shouldn't be any cases where a filter is enabled but there are no values to choose from. So when this happens it indicates either a configuration problem -which should be fixed, a code bug -which should be fixed, or a networking or GeoServer issue -which we want to know about. So we need to make sure that we find out about any of these things *before* we silently hide the only notification we might currently have (i.e. the behaviour which @kereid observed).

**Comment by pblain** [comment] 2015-07-28 06:28
Agree.  This may belong in the content repo.  If the config is correct we have a more serious bug.

**Comment by dnahodil** [comment] 2015-07-28 07:29
If there are *never* any options for those drop downs then it's probably content. If there normally are options and it only *occasionally* doesn't have them then it's a Portal bug or networking/GeoServer bug. I suspect it's the latter. @kereid was this spotted in systest or prod, and was it a one-off occurrence?

**Comment by pblain** [comment] 2015-08-03 07:32
I encountered this on the weekend. I refreshed and it went away.  Must be intermittent.

**Comment by danfruehauf** [comment] 2015-08-10 02:07
Just happened on a "demo" we had to some AWS people while using 3G with pretty crappy reception. I'd guess this is related to a timeout of the get filter values request - but it's only a guess.

**Comment by dnahodil** [comment] 2015-08-10 05:34
If this request takes a long time on the server (close to 30s or whatever the timeout is) it would be nice to know when this happens. I assume @pblain and @kereid were on pretty fast connections so it wouldn't be all down to network speed, I think.

**Comment by danfruehauf** [comment] 2015-08-10 06:12
@dnahodil So when you open step 2, we're looking at ~100 requests. On a fast connection (like ours), it takes 8s or so. I guess on a slower connection I can see it taking more than 30s for the whole page. Since all of the requests are fired more or less at the same time, it is likely that some of them *might* time out. The problem is probably at the client's end, but we can probably do something on our end as well, in terms of error handling.

**Comment by dnahodil** [comment] 2015-08-10 06:18
Yeah, I guess the filter requests are competing with tile requests as well.

**Comment by dnahodil** [comment] 2015-08-10 06:19
Hmm. Is there any way we could prioritise requests, maybe?
So base layer tiles requests go off first, then data layer tile requests, and then filters, styles, etc.

**Comment by danfruehauf** [comment] 2015-08-10 06:21
Actually when I last checked, the filters come first.

But no idea, I should be the one asking *you* about JS stuff!

**Comment by danfruehauf** [comment] 2015-08-10 07:22
First, how to reproduce:
 * Set a `sleep(40000)` in the function `getFilterValues` in `LayerController.groovy`
 * Add a layer
 * `getFilterValues` times out and we handle it like an error

So, a call for help and advise, @pblain @kereid:
After some discussions with @dnahodil and looking at the code I realized that this error is actually handled well in the code. There is a proper error handler + it sends a log in the form of `log.info` and sets text in the dropdown menu which reads `Filtering of this collection is not available at this time.`.

In terms of fixing the problem we can look at a few options:
 1. Change the wording of the text
 2. Add an error icon
 3. A combination of 1 and 2
 4. Hide the filter completely
 5. Add a `refresh` button if the filter values fail to load. This will be more along the lines of a feature rather than a bug fix and should probably be scoped out a bit better

So?
@dnahodil and me were thinking that maybe the confusion stems from the text in the dropdown menu not being set to something meaningful enough. However in terms of fixing this

**Comment by pblain** [comment] 2015-08-13 06:17
The current response to the error is fine (option 0).  What isn't fine is that the timeout occurs in the first place.

**Comment by pblain** [comment] 2015-08-13 06:47
@danfruehauf , can we make the request for possible values AFTER all tiles have loaded?

**Comment by dnahodil** [comment] 2015-08-13 07:01
I had a thought about how these browser request collisions might be addressed but I'm not sure if it's achievable. We'd need to have a play with it.

**Comment by danfruehauf** [comment] 2015-08-13 07:02
@dnahodil Talk to me?

I started reading a bit more on AJAX scheduling in browsers, I'm a bit of a rookie in that.

**Comment by dnahodil** [comment] 2015-08-13 07:14
I haven't looked into it more than when we spoke the other day.

I was just thinking that it seemed to be a similar problem as the bug is GeoServer. The problem isn't that the request takes above the timeout (30s) but that the timeout starts counting before the request is really being made by the browser (the browser will only make a limited number of requests and they're being eaten up by tiles, etc.). So if there was a place where we could queue requests and ensure that only the number that the browser will happily handle are actually being performed at any time then we wouldn't get timeouts for things that actually might finish more quickly.

Most of the request from the Portal are wrapped into proxy URLs so it seemed like we probably 'know' the times when these requests are being made. I'm just not sure if we can make them on other code's behalf.

**Comment by dnahodil** [comment] 2015-08-13 07:21
If they were all ALAX requests I think we'd be able to do it easily. But they aren't...

**Comment by danfruehauf** [comment] 2015-08-13 07:25
If they are not AJAX, then what are they?

**Comment by dnahodil** [comment] 2015-08-13 07:26
Normal resource requests, I think. Just loading images, etc.

**Comment by danfruehauf** [comment] 2015-08-13 07:27
Ohhhh, I see what you mean, openlayers...

**Comment by danfruehauf** [comment] 2015-08-14 03:37
Trying to simulate that problem I did the following:
 * Add a 4s delay for every proxy request
 * Add a 4s delay for every filter request
 * Still works fine

Using JMeter I recorded a scenario for argo loading. Then ran the scenario with 100 simultaneous users (generating some good load) and then tried to access the webapp. Didn't fail even once.

Reduce timeout in webapp from 30s to 1s, also reduce `MaxKeepAliveRequests` to 1, to potentially generate more timeouts. The result was that the portal breaks quite quickly and no one cares too much about that filter request not loading.

Did some more reading on AJAX in the browser and got to that pretty interesting article:
http://www.coderanch.com/t/631345/blogs/Maximum-concurrent-connection-domain-browsers

Unfortunately it wouldn't help us much :/

**Comment by danfruehauf** [comment] 2015-08-14 07:41
Talking to @jonescc he had tried running it in chrome with bandwidth throttling of 50Kbps and 500ms latency. Things still worked. Slow as hell, but worked.

I was looking at the apache and squid logs for `getFilterValues` requests from the Monday when I saw it failing during demo and none of those requests ever failed (all returned `200 OK`). This means a browser timeout.

Not sure how to proceed from here.

**Comment by danfruehauf** [comment] 2015-08-14 08:31
@jonescc had identified the problem is actually in portal getting a 500 error. Behind the scenes, geoserver actually failed to serve this request:
```
10 Aug 11:56:06 ERROR [geoserver.ows] - 
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at au.org.emii.geoserver.extensions.filters.LayerFiltersService.uniqueValues(LayerFiltersService.java:82)
        at sun.reflect.GeneratedMethodAccessor343.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.geoserver.ows.Dispatcher.execute(Dispatcher.java:839)
        at org.geoserver.ows.Dispatcher.handleRequestInternal(Dispatcher.java:280)
        at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:153)
        at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:48)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:923)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:852)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:882)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:778)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.geoserver.filters.ThreadLocalsCleanupFilter.doFilter(ThreadLocalsCleanupFilter.java:28)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:75)
        at org.geoserver.wms.animate.AnimatorFilter.doFilter(AnimatorFilter.java:71)
        at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:71)
        at org.geoserver.filters.SpringDelegatingFilter.doFilter(SpringDelegatingFilter.java:46)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.geoserver.platform.AdvancedDispatchFilter.doFilter(AdvancedDispatchFilter.java:50)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:311)
        at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:69)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:116)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:83)
        at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:73)
        at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:92)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323)
j        at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:69)
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113)
        at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:73)
        at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:92)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323)
        at org.geoserver.security.filter.GeoServerAnonymousAuthenticationFilter.doFilter(GeoServerAnonymousAuthenticationFilter.java:54)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323)
        at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:69)
        at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilter(BasicAuthenticationFilter.java:150)
        at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:73)
        at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:92)
        at org.geoserver.security.filter.GeoServerBasicAuthenticationFilter.doFilter(GeoServerBasicAuthenticationFilter.java:83)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323)
        at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:69)
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87)
        at org.geoserver.security.filter.GeoServerSecurityContextPersistenceFilter$1.doFilter(GeoServerSecurityContextPersistenceFilter.java:53)
        at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:73)
        at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:92)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323)
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:173)
        at org.geoserver.security.GeoServerSecurityFilterChainProxy.doFilter(GeoServerSecurityFilterChainProxy.java:135)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:259)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.geoserver.filters.LoggingFilter.doFilter(LoggingFilter.java:76)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.geoserver.filters.SessionDebugFilter.doFilter(SessionDebugFilter.java:48)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.geoserver.filters.FlushSafeFilter.doFilter(FlushSafeFilter.java:44)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.vfny.geoserver.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:109)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:620)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at au.org.emii.geoserver.extensions.filters.layer.data.io.PossibleValuesReader.read(PossibleValuesReader.java:66)
        at au.org.emii.geoserver.extensions.filters.LayerFiltersService.getUniqueValuesDocument(LayerFiltersService.java:106)
        at au.org.emii.geoserver.extensions.filters.LayerFiltersService.uniqueValues(LayerFiltersService.java:79)
        ... 88 more
Caused by: java.io.IOException
        at org.geotools.jdbc.JDBCDataStore.getAggregateValue(JDBCDataStore.java:1471)
        ... 95 more
Caused by: org.postgresql.util.PSQLException: ERROR: relation "profile_summary" does not exist
  Position: 93
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2062)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1795)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:257)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:479)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:353)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:252)
        at org.apache.tomcat.dbcp.dbcp.DelegatingStatement.executeQuery(DelegatingStatement.java:208)
        at org.apache.tomcat.dbcp.dbcp.DelegatingStatement.executeQuery(DelegatingStatement.java:208)
        at org.geotools.jdbc.JDBCDataStore.getAggregateValue(JDBCDataStore.java:1451)
        ... 95 more

```

**Comment by danfruehauf** [comment] 2015-08-17 04:06
Reproducible by running:
```
for i in `seq 1 1000`; do curl -v "http://geoserver-123.aodn.org.au/geoserver/wms?request=uniqueValues&service=layerFilters&version=1.0.0&workspace=imos&layer=argo_profile_map&propertyName=project_name&_dc=$i"; done
```

**Comment by pmbohm** [comment] 2015-08-26 01:39
### So to summarize:
Craigs error log extract looks like a config issue
```
ERROR: relation "profile_summary" does not exist
```
Which is separate to Dan's request
 (fails for me if I run it only a few times)
```
for i in `seq 1 3`; do curl ......
```
Run once and its ok. So the real bug is at Geoserver?

**Comment by jonescc** [comment] 2015-08-26 02:06
Yes there were another couple of errors in the geoserver log getting uniquevalues for argo at 11:33 which I assume is when you tried this.

**Comment by julian1** [comment] 2015-08-26 05:56
Error on db is,

```
2015-08-17 03:51:28 GMT 192.168.100.1 geoserver_123_12_nsp_mel harvest 3111 42P01ERROR:  relation "profile_summary" does not exist at character 93
2015-08-17 03:51:28 GMT 192.168.100.1 geoserver_123_12_nsp_mel harvest 3111 42P01STATEMENT:  SELECT distinct("project_name") FROM (select 
         profile_summary.*,
         indexed_file.*
          from profile_summary
          left join indexed_file
            on file_id = indexed_file.id
        ) as "vtable"

```

But this view definittely exists
```
harvest=# \dv argo.profile_summary 
            List of relations
 Schema |      Name       | Type | Owner 
--------+-----------------+------+-------
 argo   | profile_summary | view | argo
(1 row)
```

There's probably an issue setting the schema_path on the jdbc connection.  A cheap way to fix *might* be to add an argo prefix the two tables referred to in the JDBC view in geoserver-config here,

https://github.com/aodn/geoserver-config/blob/master/workspaces/imos/JNDI_argo/argo_profile_map/featuretype.xml

**Comment by jonescc** [comment] 2015-08-26 06:01
Yeah, but its also horrible having to specify the schema name every where - what if you want to change it.

Probably related to sql views?  Another way to fix is to move this 'view' back into the database and use a normal data store.

**Comment by dnahodil** [comment] 2015-08-26 06:03
Do we know how often this request is failing? e.g. 1-in-50, 1-in-10?

**Comment by julian1** [comment] 2015-08-26 06:13
I did say cheap ;-).

@dnahodil The code path for getting connections when the virtual table gets hit is a bit different. If I had to guess - I'd say that the code is borrowing a pooled jdbc connection that has the schema_path set up correctly from a previous non-virtual table request. That's why it mostly works.

**Comment by pmbohm** [comment] 2015-08-26 06:36
1 in N number of times guaranteed!

**Comment by pmbohm** [comment] 2015-08-27 00:28
## So to conclude:
Using virtual tables in Geoserver has issues which led to this bug.
## The 'Best' answer
Craigs answer; `"move this 'view' back into the database and use a normal data store."` should be fixed in the content repo. Using virtual views in Geoserver should be abandoned.
If this isn't practical then @julian1's answer to add schema prefixes should always be utilized.

**Comment by jonescc** [comment] 2015-08-28 05:39
OK, so I had a bit of a look at what Geoserver's doing and there is no easy fix that I can see to pick up the schema entered when creating the data store.

The issue here as that for postgres the default schema needs to be set on the connection - which is not possible when we are using one jndi data connection for all harvest data stores, or needs to be picked up from the search path specified for the user which again isn't possible because we are using one jndi resource for all harvest data stores.

For 'normal' jndi/jdbc data stores we are dealing with one table and geoserver can add the schema specified in the data store when querying the database.  This is not possible for an sqlview - geoserver would need to parse the sql and modify it to insert schema qualifiers - not a good idea.

So ways to resolve this issue are:

a) create a separate jndi resource for data stores that need to support sql views (I think this is how we used to do it when this sql view was defined - its not even possible to create the sql view now the way we have it setup) - this isn't a good option
b) specify the search path to use for the data store in the session startup parameter (e.g. set search_path to argo, public;)
c) add the schema qualifier to tables in the sql - I'm not a fan of that one
d) move the view to the database so geoserver can add the schema qualifier again to the view name

Personally I think the views belong in the database so no need to look at work arounds.

To be resolved under https://github.com/aodn/content/issues/130

**Closed by jonescc** 2015-08-28 05:39 UTC
Labels: bug
