### ISSUE TITLE
Metadata is downloaded even when there is no data

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#1559] opened 2015-01-15 02:04 UTC
Instance name: IMOS
            App version: 3.38.2
            Build date: Tue Jan 13 15:51:19 EST 2015
            Build number: 315
            Git ref: 0ee9ca47caaa1bba812ba527564a761b678b2d7a

Steps to reproduce:

Add AATAMS near real-time data collection to the map draw a bounding box where clearly there is no data. Proceed to step 3. Click download as csv

What should happen:

either empty csv or no download at all

What does happen:

Csv is downloaded and contains only metadata

**Comment by jonescc** [comment] 2015-01-21 03:56
A csv containing metadata only is an empty csv!

We do disable the download button where it's possible to work out in advance easily that there is no data to download (for BODAAC downloads i.e. where download as unsubsetted netcdf files is available).

@pblain tells me this is not a bug so closing.

**Closed by jonescc** 2015-01-21 03:56 UTC
Labels: bug
