### ISSUE TITLE
Portal base map doesn't (always/fully) load on first map view

### ISSUE THREAD

**Issue by jachope** [aodn/aodn-portal#2818] opened 2019-09-16 03:30 UTC
Originally loaded here - https://github.com/aodn/issues/issues/519

**Steps to reproduce:**
Open the portal in a fresh tab (or reload it), and select any collection - ideally not a gridded one so you can see the base map.

**What happens:**
Sometimes (maybe one in 4 tries?) the base map doesn't load completely (or at all) when the collection is first displayed on the map.) E.g.:
Screenshot from 2019-09-11 09-57-01

As you pan/zoom, or if you switch to simple baselayer and back, it does eventually load the missing tiles.

**What should happen**
Obviously it would be nicer if the base map was fully loaded right from the start.

**Comment by pmbohm** [comment] 2019-09-19 02:34
@mhidas I have seen this happen to me in the past. At this moment it is impossible to reproduce, but this could be some more of the portal server load issues from WMS proxying?

@lwgordonimos I'm seeing logged errors such as these
`_sourcecategory = "prod/aodn-portal/nginx/error" and "Connection refused" `

**Comment by pmbohm** [comment] 2019-09-23 00:41
Closing as its unreproducible on my machine.
@mhidas to test with different browser

**Closed by pmbohm** 2019-09-23 00:41 UTC
Labels: T1 - IMOS, T2 - O&M - Continuous Improvement, T3 Information Infrastructure

**Comment by mhidas** [comment] 2019-09-23 02:27
I couldn't reproduce it either in Google Chrome (I was using Chromium before).
