### ISSUE TITLE
Portal download Internal Server Error due to Captcha response issue

### ISSUE THREAD

**Issue by jonescc** [aodn/aodn-portal#2365] opened 2016-10-20 05:33 UTC
### To Reproduce

Attempt to do a number of GoGoDuck downloads in a row (I was testing and had submitted around 13 requests)

### What happens

At some point I started getting an Internal Server Error - Unable to create subsetting job.  Please recheck the parameters you provided and try again.

There were two elastic beanstalk instances running and when I looked at the logs for one I could see the following errors:

```
2016-10-20 05:16:48,877 INFO  [http-nio-8080-exec-1] [] grails.app.services.au.org.emii.portal.DownloadAuthService  - Seems like 131.217.255.204 might be trying to abuse us, '9' downloads in '10' minutes
2016-10-20 05:16:48,877 INFO  [http-nio-8080-exec-1] [] grails.app.controllers.au.org.emii.portal.AsyncDownloadController  - Could not verify challenge 'null' from '131.217.255.204'
2016-10-20 05:16:48,888 ERROR [http-nio-8080-exec-1] [] grails.app.controllers.au.org.emii.portal.AsyncDownloadController  - Problem registering new aggregator job with type 'wps' and parameters: '[server:http://geoserver-wps-systest.aodn.org.au/geoserver/wps, email.to:Craig.Jones@utas.edu.au, email:[to:Craig.Jones@utas.edu.au], jobType:GoGoDuck, mimeType:application/x-netcdf, jobParameters.layer:gsla_dm00_timeseries_url, jobParameters:[layer:gsla_dm00_timeseries_url, subset:TIME,1993-01-01T00:00:00.000Z,1993-01-07T00:00:00.000Z;LATITUDE,-32.23486328125,-31.366943359375;LONGITUDE,111.53869628906,113.46130371094], jobParameters.subset:TIME,1993-01-01T00:00:00.000Z,1993-01-07T00:00:00.000Z;LATITUDE,-32.23486328125,-31.366943359375;LONGITUDE,111.53869628906,113.46130371094, _dc:1476940608835, controller:asyncDownload]'
java.lang.Exception: Could not verify challenge (captcha), denying download
        at au.org.emii.portal.AsyncDownloadController.verifyChallengeResponse(AsyncDownloadController.groovy:27)
        at au.org.emii.portal.AsyncDownloadController$_closure1.doCall(AsyncDownloadController.groovy:38)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
2016-10-20 05:17:00,483 INFO  [http-nio-8080-exec-8] [] grails.app.services.au.org.emii.portal.DownloadAuthService  - Seems like 131.217.255.204 might be trying to abuse us, '9' downloads in '10' minutes
2016-10-20 05:17:00,485 INFO  [http-nio-8080-exec-8] [] grails.app.controllers.au.org.emii.portal.AsyncDownloadController  - Could not verify challenge 'null' from '131.217.255.204'
2016-10-20 05:17:00,487 ERROR [http-nio-8080-exec-8] [] grails.app.controllers.au.org.emii.portal.AsyncDownloadController  - Problem registering new aggregator job with type 'wps' and parameters: '[server:http://geoserver-wps-systest.aodn.org.au/geoserver/wps, email.to:Craig.Jones@utas.edu.au, email:[to:Craig.Jones@utas.edu.au], jobType:GoGoDuck, mimeType:application/x-netcdf, jobParameters.layer:gsla_dm00_timeseries_url, jobParameters:[layer:gsla_dm00_timeseries_url, subset:TIME,1993-01-01T00:00:00.000Z,1993-01-07T00:00:00.000Z;LATITUDE,-32.23486328125,-31.366943359375;LONGITUDE,111.53869628906,113.46130371094], jobParameters.subset:TIME,1993-01-01T00:00:00.000Z,1993-01-07T00:00:00.000Z;LATITUDE,-32.23486328125,-31.366943359375;LONGITUDE,111.53869628906,113.46130371094, _dc:1476940620442, controller:asyncDownload]'
java.lang.Exception: Could not verify challenge (captcha), denying download
        at au.org.emii.portal.AsyncDownloadController.verifyChallengeResponse(AsyncDownloadController.groovy:27)
        at au.org.emii.portal.AsyncDownloadController$_closure1.doCall(AsyncDownloadController.groovy:38)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
2016-10-20 05:23:09,751 INFO  [http-nio-8080-exec-5] [] grails.app.services.au.org.emii.portal.DownloadAuthService  - Seems like 131.217.255.204 might be trying to abuse us, '4' downloads in '10' minutes
2016-10-20 05:23:09,752 INFO  [http-nio-8080-exec-5] [] grails.app.controllers.au.org.emii.portal.AsyncDownloadController  - Could not verify challenge 'null' from '131.217.255.204'
2016-10-20 05:23:09,754 ERROR [http-nio-8080-exec-5] [] grails.app.controllers.au.org.emii.portal.AsyncDownloadController  - Problem registering new aggregator job with type 'wps' and parameters: '[server:http://geoserver-wps-systest.aodn.org.au/geoserver/wps, email.to:Craig.Jones@utas.edu.au, email:[to:Craig.Jones@utas.edu.au], jobType:GoGoDuck, mimeType:application/x-netcdf, jobParameters.layer:gsla_dm00_timeseries_url, jobParameters:[layer:gsla_dm00_timeseries_url, subset:TIME,1993-01-01T00:00:00.000Z,1993-01-07T00:00:00.000Z;LATITUDE,-32.23486328125,-31.366943359375;LONGITUDE,111.53869628906,113.46130371094], jobParameters.subset:TIME,1993-01-01T00:00:00.000Z,1993-01-07T00:00:00.000Z;LATITUDE,-32.23486328125,-31.366943359375;LONGITUDE,111.53869628906,113.46130371094, _dc:1476940989542, controller:asyncDownload]'
java.lang.Exception: Could not verify challenge (captcha), denying download
        at au.org.emii.portal.AsyncDownloadController.verifyChallengeResponse(AsyncDownloadController.groovy:27)
        at au.org.emii.portal.AsyncDownloadController$_closure1.doCall(AsyncDownloadController.groovy:38)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

Note that I wasn't asked to enter a captcha in the browser

### What I expect to happen

I enter challenge response details if necessary and my download is submitted

**Comment by jonescc** [comment] 2016-10-20 06:00
May be a timing thing - I noticed that sometimes it takes a while for the Captcha to be populated - so may have just hit the submit button before the captcha was returned.  Either way it happened to me a few times and I was in a race.

**Comment by jonescc** [comment] 2016-10-20 06:44
OK so even when I wait sometime for a captcha to be returned it sometimes it doesn't get returned and when I submit I get the error - so something going on here.

**Comment by lwgordonimos** [comment] 2016-10-20 23:41
@jones it seems like the "I understand, download" button should be disabled until the CAPTCHA text box is validated as containing a 6 character string?

**Comment by jonescc** [comment] 2016-10-20 23:50
Sometimes the captcha text box is not presented ever - so there would never be a way to download.   Its easy enough to reproduce - took me around 6 download attempts just a minute ago.

**Comment by lwgordonimos** [comment] 2016-10-20 23:58
Ok yeah, sounds like that is separate then. Probably needs both: better detection of the success/failure (retry?) of the captcha load and the validation as well.

**Comment by bhasin85** [comment] 2016-10-21 03:36
@jonescc  I was unable to reproduce the error on development and systest environment. I tried submitting around 15  requests. Captcha worked fine for me. Let's work on this one together on Monday.

**Comment by jonescc** [comment] 2016-10-23 20:08
Works fine with only one elastic beanstalk instance running.  I was able to reproduce this easily with two running as per description above.

**Comment by julian1** [comment] 2016-10-23 20:28
If there are two instances, and there is some kind of connection delegation (DNS based?) then maybe each geoserver app is maintaining it's own client session-state about the captcha under different cookie identifiers. 

We saw this before with geoserver authentication when running two geoservers. Depending on which geoserver was delegated to - the user would be recognized as authenticated or non authenticated, depending on whichever geoserver was the active when the user first authenticated.

**Comment by bhasin85** [comment] 2016-10-23 22:33
@julian1  I believe that we can easily fix this at ELB level by enabling sticky session (just a flag).

**Comment by lwgordonimos** [comment] 2016-10-23 22:58
@bhasin85 A flag and also an expiration value. As discussed, I've added the following to the systest config:

```yaml
option_settings:
  aws:elb:policies:
    Stickiness Cookie Expiration: 300
    Stickiness Policy: true
```

**Comment by bhasin85** [comment] 2016-10-23 22:59
@lwgordonimos  
![giphy](https://cloud.githubusercontent.com/assets/2552378/19630179/94a6f2b6-99d0-11e6-98f8-1b53d1d3e7d6.gif)

**Comment by anguss00** [comment] 2016-10-25 05:27
Fixed by https://github.com/aodn/chef-private/pull/2105/commits/8782b6708028a75ee942e75df4d563441aebf0d0

**Closed** 2016-10-25 05:27 UTC
Labels: bug
