### ISSUE TITLE
Email notification sent wrong for GoGoDuck

### ISSUE THREAD

**Issue by fxmzb123** [aodn/aodn-portal#2137] opened 2016-03-04 00:06 UTC
# How to reproduce

1. Go to dataportal.tpac.org.au
2. Select dataset Climate Futures for Tasmania (Pres_C64-60k_ukhadcm3_B1-ct-uf)
3. In step2, select time front 2100/12/01 to 2101/01/01 and click 'next'
4. In step3, select download as netcdf, and put in email address.
5. Click 'I understand, download'
6. Go you email box.

# What happends

2 emails, 'IMOS download request registered' and 'IMOS download available' are sent. The second email 'IMOS download available' is sent before the job is finished and the download is available.

# What should happen
The second email 'IMOS download available' should be sent after the job is finished and the download is available

**Comment by danfruehauf** [comment] 2016-03-04 00:32
We send 2 emails. One to let the user know the job was registered + a tracking URL. Second email is to notify it is done. It is by design.

Is that what you are referring to?

**Comment by fxmzb123** [comment] 2016-03-04 00:44
The problem is the second email is sent before the job is done.
The second email should be sent after the job is done.

**Comment by danfruehauf** [comment] 2016-03-04 01:11
@fxmzb123 Can you please make the ticket look like #2132 (in terms of templating etc)?

**Comment by rogerproctor** [comment] 2016-04-04 00:50
This issue seems to be a result of the implementation on TPAC, because it works as expected on the IMOS portal.

**Comment by jonescc** [comment] 2016-04-04 01:35
Have just looked at this with @fxmzb123, GeoServer is sending the job finished notification to the portal prior to copying outputs to the output directory resulting in an email being sent before all processing has actually been completed.  For the example given above, the copy (400mb) takes a significant amount of time for some reason making this issue obvious in the TPAC portal.

**Comment by pblain** [comment] 2016-04-04 07:13
@fxmzb123 - sounds like you need to look at why the copy process is taking so long.  I'll close this for now - until you've looked into it.

**Closed by pblain** 2016-04-04 07:13 UTC
Labels: bug
