### ISSUE TITLE
Facets not finding all records

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#1595] opened 2015-02-20 04:31 UTC
Instance name: IMOS
            App version: 3.41.2
            Build date: Thu Feb 19 09:38:07 AEDT 2015
            Build number: 357
            Git ref: e9cec741231a49f2774f7397860b0be6cbdbb353

I think this one may be the same as #1451 but thought I'd log a new fresh bug.

Steps to repeat:

1.Compare numbers of facets on systest to  prod

2.Manually count records of -for example- moorings in default results list

What should happen:

1.They are the same

2. They are the same

What does happen:

1. Prod has more results

2. The count in the default list is more than the number next to the facets list

**Comment by jkburges** [comment] 2015-03-09 23:26
@kereid @atkinsn @dnahodil, I need a bit of clarification on the expected behaviour, regarding point 1 in "what does happen".  If I understand things correctly, the content (i.e. geonetwork search results/facets) should be exactly the same between `prod` and `systest`, while `rc` may differ (often `rc` will have some more results, due to new collections being added).

So the fact that results for `rc` differ is ok (but not the fact that `prod` differs)?

**Comment by atkinsn** [comment] 2015-03-10 02:04
Not sure if this is influencing these results at all. But currently the back harvest from prod to rc is turned off due to Loz's gogoduck testing.

**Comment by danfruehauf** [comment] 2015-03-13 00:26
This ticket should change so that it reads that there are different results between prod and systest. Differences between any of those environments and rc are out of dev control and should be opened on the content repository if at all.

**Comment by danfruehauf** [comment] 2015-03-13 00:35
In terms of configuration the backup used on systest could have lagged for up to 2 days behind production geonetwork. I'll fix that.

At the moment I don't see inconsistencies between systest and prod.

**Comment by danfruehauf** [comment] 2015-03-16 06:09
@kereid Lets leave that open. If this doesn't happen in the next couple of weeks, we'll close it. If it does, we'll try to see if it's related to changes Nat has done on production and weren't propagated to systest because the backup runs only daily.

**Comment by danfruehauf** [comment] 2015-03-16 06:52
@pblain asked me to close it. Should be reopened if it happens again.

**Closed** 2015-03-16 21:59 UTC
Labels: bug

**Comment by kereid** [comment] 2015-03-24 01:02
@danfruehauf I believe this did happen however can't 100% confirm as I didn't see it, but @jachope had written down some questions for me thismorning with specific collection names exactly as they appeared and also a collection that was not loading but then when we tried to look at them thismorning the names were different and the collection was loading correctly.

My fault for not wording @jachope up on the issue, but next testing we will keep an eye out for inconsistencies.
