### ISSUE TITLE
The curious case of the disappearing mooring.......

### ISSUE THREAD

**Issue by atkinsn** [aodn/aodn-portal#2559] opened 2017-09-13 06:05 UTC
Steps to reproduce
1. Select the following layer on the Portal - IMOS - SRS Satellite Altimetry Calibration and Validation Sub-Facility
2. Go to Step 2, select the hand, place the moorings north of Tasmania in the centre of the screen, and zoom in 1 click

What should happen
You should be able to see all 4 moorings still

What does happen
The mooring on the left disappears.

Note the layer works correctly in geoserver - http://geoserver-123.aodn.org.au/geoserver/imos/wms?service=WMS&version=1.1.0&request=GetMap&layers=imos:srs_altimetry_timeseries_map&styles=&bbox=145.591995239258,-43.2999992370605,147.664001464844,-40.6419982910156&width=598&height=768&srs=EPSG:4326&format=application/openlayers

**Comment by pblain** [comment] 2017-09-19 03:13
I couldn't reproduce this. 
![image](https://user-images.githubusercontent.com/2802359/30574231-fa4db5d6-9d3b-11e7-8d6b-b0bb5869d8c6.png)

**Comment by atkinsn** [comment] 2017-09-19 05:20
Sorry, the zoom in 1 click happens after "zoom to collection".

**Comment by pblain** [comment] 2017-09-19 05:49
Thanks Nat!

**Comment by pblain** [comment] 2017-09-19 06:25
@atkinsn - should this be allocated to me - or is it allocated to @smancini because it's a content issue?

**Comment by atkinsn** [comment] 2017-09-19 06:35
Sorry I don't know how the allocations should work, but I think Seb suggested it should be him (not sure of reasoning).

**Comment by pblain** [comment] 2017-09-19 06:46
Thanks Nat. @smancini - feel free to allocate it to me if you want us to look at it next iteration.

**Comment by smancini** [comment] 2017-09-22 00:29
It might be a cache issue

**Comment by pmbohm** [comment] 2017-10-10 22:19
Related to https://github.com/aodn/issues/issues/118

**Comment by pmbohm** [comment] 2017-10-10 23:30
Note: Using the filters (matching the point/line) will show the missing information in getMap tiles

From aodn/issues#118
#### Missing line in Tilecache:
https://tilecache.aodn.org.au/geowebcache/service/wms?LAYERS=imos%3Asoop_ba_trajectory_map&TRANSPARENT=TRUE&VERSION=1.1.1&FORMAT=image%2Fpng&EXCEPTIONS=application%2Fvnd.ogc.se_xml&SERVICE=WMS&REQUEST=GetMap&STYLES=&QUERYABLE=true&SRS=EPSG%3A4326&BBOX=-180,-42.1875,-177.1875,-39.375&WIDTH=256&HEIGHT=256



#### Ok direct from Geoserver:
http://geoserver-123.aodn.org.au/geoserver/imos/wms?LAYERS=imos%3Asoop_ba_trajectory_map&TRANSPARENT=TRUE&VERSION=1.1.1&FORMAT=image%2Fpng&EXCEPTIONS=application%2Fvnd.ogc.se_xml&SERVICE=WMS&REQUEST=GetMap&STYLES=&QUERYABLE=true&SRS=EPSG%3A4326&BBOX=-180,-42.1875,-177.1875,-39.375&WIDTH=256&HEIGHT=256

![imos-soop_ba_trajectory_map](https://user-images.githubusercontent.com/1066981/31413632-f2f77232-ae65-11e7-844b-58d0ee9447e4.png)

**Comment by pmbohm** [comment] 2017-10-12 03:21
Closing as the issue is at aodn/issues#118

**Closed by pmbohm** 2017-10-12 03:21 UTC
Labels: bug
