### ISSUE TITLE
Selecting a project does not subset stations

### ISSUE THREAD

**Issue by Abulos** [aodn/aodn-portal#2926] opened 2022-07-07 00:05 UTC
This issue tracker is only for AODN Portal issues.

### Steps to reproduce the issue
1.Select Platform-Vessels-Small Boat
2.Select IMOS - Combined Biogeochemical parameters (reference stations)
3.Select Project-NRS or SARDI
4.Check pulldown menu in station

### Expected behaviour
Selecting project should subset stations

### Actual behaviour
No subsetting occurs - still see all stations

### Screenshots.
NA

### What version of the aodn portal are you using?
No idea - the one on the internet today - you should provide some instructions on where to obtain this information

### Which browser are you using?
Firefox 91.11.0esr (64-bit)

### Any extra information that might be useful in the debugging process.
NA

**Comment by kereid** [comment] 2022-07-07 00:27
Hi @Abulos thank you for your feedback, we are aware of the issue with this collection and are investigating (it is loaded in a private repository),  the issue is that the default view of the collection does not actually show all of the project points, you may note if you watch the map around South Australia when you select SARDI there are a substantial number of points added on to the map.

The version number of the Portal can be found on the landing page bottom left text.

**Comment by craigrose** [comment] 2023-03-07 06:08
https://portal.aodn.org.au/search?uuid=b442c3e8-3d30-48ad-b144-680afd848167

**Comment by craigrose** [comment] 2023-03-09 02:23
@vfisaac 
This is expected behaviour. Won't fix because requires adding new features to Portal.

**Closed by craigrose** 2023-03-09 02:23 UTC
Labels: enhancement, wont fix
