### ISSUE TITLE
Python Downloads not available for all collections

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2374] opened 2016-10-26 04:50 UTC
Steps to reproduce:

Add Bio-Acoustic ships of opportunity or AusCPR phytoplankton database to the map. Proceed to step three and look at drop down

What happens:
There is not an option to download a python script

What should happen:
There should be a python download option? I'm not 100% certain on this that there should be a download for python for all collections, but I can't recall not seeing it for any collections but that's not to say that it hasn't been there before.

Can someone please confirm if this is actually an issue or if that particular download option needs to be set up for each collection and just hasn't been done?

**Comment by jonescc** [comment] 2016-10-26 20:41
Apparently the python download option will only be shown for a collection with an online resource in the metadata containing 'OGC:WFS-1.0.0-http-get-capabilities'.  So this would be a content issue.  

I'm not sure this is the best way to indicate that a python download option should be made available.  Its a misuse of this protocol.  But its probably not a bug , more a need to rethink this feature.

**Comment by jonescc** [comment] 2016-10-26 20:45
I think we are moving to a list of files protocol - so we should probably enable python download options, list of files and files download options whenever that protocol is used instead of specifying them all separately.

**Comment by jonescc** [comment] 2016-10-26 21:33
Actually, python download should be made available for wfs downloads not file lists - so this looks OK.  Working as designed as wfs download does not apply to this collection.

**Closed by jonescc** 2016-10-26 21:33 UTC
Labels: bug

**Comment by jonescc** [comment] 2016-10-26 21:37
This is a content issue as the wfs download option has not been specified for these colletions
