### ISSUE TITLE
Multi WFS or MARVL3 issue

### ISSUE THREAD

**Issue by pblain** [aodn/aodn-portal#2275] opened 2016-08-26 01:20 UTC
## Steps to reproduce
1. Go to portal-systest
1. Select MARVL3 - Australian shelf temperature data atlas
1. Select a small bounding box
1. Go to step 3
1. Select download as
1. Choose the second CSV option : Temperature observations

## What happens
The spinner spins for some time and then:

![image](https://cloud.githubusercontent.com/assets/2802359/17991089/119899ee-6b7f-11e6-9bbb-188e58d2d9af.png)

**Comment by pmbohm** [comment] 2016-09-01 04:50
portal-systest produced a console error first time which have been the cause of this bug.
But I'm not able to reproduce again. could it be data?

The error was not producible (even once) in dev environment using current master

**Comment by bhasin85** [comment] 2016-09-08 05:42
Unable to reproduce on systest.

**Comment by kereid** [comment] 2016-09-15 22:02
Seeing this today
![error](https://cloud.githubusercontent.com/assets/2906602/18569102/ee133342-7be3-11e6-9fef-c379154d2098.png)

**Comment by kereid** [comment] 2016-09-20 05:57
@pblain why did you close this I saw it 4 days ago during testing?

**Comment by kereid** [comment] 2016-09-20 06:01
And to confirm I just reproduced it now to make sure I wasn't going crazy :-)

**Comment by pblain** [comment] 2016-09-20 07:11
@kereid - I thought @bhasin85 said in planning that it was fixed.  But feel free to reopen if that's not the case.  Means we have one more bug than we planned for.

**Comment by pblain** [comment] 2016-09-20 07:12
P.S. it will need a ticket on the board

**Comment by bhasin85** [comment] 2016-09-21 00:42
Able to reproduce the issue. This happens occasionally and is related to timeout. 
![2275](https://cloud.githubusercontent.com/assets/2552378/18693797/fab00172-7fe7-11e6-9451-670b1f2fc048.png)

**Comment by lwgordonimos** [comment] 2016-09-21 00:59
After looking in a couple of places, I suspect this is not an issue with the systest Portal specifically.

The database on 14-nec-hob seems to be in a pretty weird state since 14-nsp-mel was superseded, so I think this is a flow on of that, and the time-outs are just a symptom of the underlying infrastructure problem (both with general slowness and database missing relations etc.).

### Portal
```bash
2016-09-21 00:20:51,113 ERROR [http-nio-8080-exec-2] [] client-log  - session ID: BEF911C84, message: Download failed,download?url=http%3A%2F%2Fgeoserver-systest.aodn.org.au%2Fgeoserver%2Fows%3FtypeName%3Dimos%3Amarvl3_raw_data%26SERVICE%3DWFS%26outputFormat%3Dcsv-with-metadata-header%26REQUEST%3DGetFeature%26VERSION%3D1.0.0%26CQL_FILTER%3DINTERSECTS(geom_bin%252CPOLYGON((148.798828125%2520-26.060546875%252C148.798828125%2520-18.150390625%252C162.685546875%2520-18.150390625%252C162.685546875%2520-26.060546875%252C148.798828125%2520-26.060546875)))&downloadFilename=MARVL3_-_Australian_shelf_salinity_data_atlas.csv&downloadToken=1474417191349,[object Object],<pre></pre>
2016-09-21 00:22:56,041 ERROR [http-nio-8080-exec-5] [] client-log  - session ID: 67E249C3B, message: Download failed,download?url=http%3A%2F%2Fgeoserver-systest.aodn.org.au%2Fgeoserver%2Fows%3FtypeName%3Dimos%3Amarvl3_raw_data%26SERVICE%3DWFS%26outputFormat%3Dcsv-with-metadata-header%26REQUEST%3DGetFeature%26VERSION%3D1.0.0%26CQL_FILTER%3DINTERSECTS(geom_bin%252CPOLYGON((146.2060546875%2520-21.9296875%252C146.2060546875%2520-16.744140625%252C159.4775390625%2520-16.744140625%252C159.4775390625%2520-21.9296875%252C146.2060546875%2520-21.9296875)))&downloadFilename=MARVL3_-_Australian_shelf_salinity_data_atlas.csv&downloadToken=1474417316572,[object Object],<pre style="word-wrap: break-word; white-space: pre-wrap;"></pre>
2016-09-21 00:24:57,641 ERROR [http-nio-8080-exec-7] [] client-log  - session ID: 2C130FD09, message: Download failed,download?url=http%3A%2F%2Fgeoserver-systest.aodn.org.au%2Fgeoserver%2Fows%3FtypeName%3Dimos%3Amarvl3_raw_data%26SERVICE%3DWFS%26outputFormat%3Dcsv-with-metadata-header%26REQUEST%3DGetFeature%26VERSION%3D1.0.0%26CQL_FILTER%3DINTERSECTS(geom_bin%252CPOLYGON((146.2060546875%2520-21.9296875%252C146.2060546875%2520-16.744140625%252C159.4775390625%2520-16.744140625%252C159.4775390625%2520-21.9296875%252C146.2060546875%2520-21.9296875)))&downloadFilename=MARVL3_-_Australian_shelf_salinity_data_atlas.csv&downloadToken=1474417437948,[object Object],<pre style="word-wrap: break-word; white-space: pre-wrap;"></pre>
2016-09-21 00:24:57,643 ERROR [http-nio-8080-exec-3] [] client-log  - session ID: 2C130FD09, message: Download failed,download?url=http%3A%2F%2Fgeoserver-systest.aodn.org.au%2Fgeoserver%2Fows%3FtypeName%3Dimos%3Amarvl3_raw_data%26SERVICE%3DWFS%26outputFormat%3Dcsv-with-metadata-header%26REQUEST%3DGetFeature%26VERSION%3D1.0.0%26CQL_FILTER%3DINTERSECTS(geom_bin%252CPOLYGON((146.2060546875%2520-21.9296875%252C146.2060546875%2520-16.744140625%252C159.4775390625%2520-16.744140625%252C159.4775390625%2520-21.9296875%252C146.2060546875%2520-21.9296875)))&downloadFilename=MARVL3_-_Australian_shelf_salinity_data_atlas.csv&downloadToken=1474417437948,[object Object],<pre style="word-wrap: break-word; white-space: pre-wrap;"></pre>
2016-09-21 00:49:03,610 ERROR [http-nio-8080-exec-3] [] client-log  - session ID: CC35EF60C, message: Download failed,download?url=http%3A%2F%2Fgeoserver-systest.aodn.org.au%2Fgeoserver%2Fows%3FtypeName%3Dimos%3Amarvl3_raw_data%26SERVICE%3DWFS%26outputFormat%3Dcsv-with-metadata-header%26REQUEST%3DGetFeature%26VERSION%3D1.0.0%26CQL_FILTER%3DINTERSECTS(geom_bin%252CPOLYGON((146.9970703125%2520-24.2587890625%252C146.9970703125%2520-19.0732421875%252C155.3466796875%2520-19.0732421875%252C155.3466796875%2520-24.2587890625%252C146.9970703125%2520-24.2587890625)))&downloadFilename=MARVL3_-_Australian_shelf_salinity_data_atlas.csv&downloadToken=1474418883471,[object Object],<pre></pre>
```
### Geoserver
```bash
21 Sep 00:47:54 ERROR [geotools.jdbc] - Failed to execute statement SELECT "file_id","abstract","url_marlin_metadata","cruise_id","data_type","url_nc","url_csv","url_plot","size","time_start","time_end","vessel_name","colour",encode(ST_AsEWKB("geom"),'base64') as "geom" FROM "srs_oc_bodbaw"."srs_oc_bodbaw_trajectory_profile_map" LIMIT 1
21 Sep 00:47:54 ERROR [geotools.jdbc] - Failed to execute statement SELECT "file_id","abstract","url_marlin_metadata","cruise_id","data_type","url_nc","url_csv","url_plot","size","time_start","time_end","vessel_name","colour",encode(ST_AsEWKB("geom"),'base64') as "geom" FROM "srs_oc_bodbaw"."srs_oc_bodbaw_trajectory_profile_map" LIMIT 1
21 Sep 00:47:54 ERROR [geoserver.ows] - 
Caused by: java.sql.SQLException: org.postgresql.util.PSQLException: ERROR: column "time_start" does not exist
Caused by: org.postgresql.util.PSQLException: ERROR: column "time_start" does not exist
21 Sep 00:47:54 ERROR [geoserver.ows] - 
Caused by: java.sql.SQLException: org.postgresql.util.PSQLException: ERROR: column "time_start" does not exist
Caused by: org.postgresql.util.PSQLException: ERROR: column "time_start" does not exist
21 Sep 00:48:03 WARN [wfs.response] - ERROR: relation "parameters_mapping.marvl3_metadata_summary" does not exist

**Comment by lwgordonimos** [comment] 2016-09-21 07:56
Evidence of exactly 60 second timeout:

```bash
$ wget "https://portal.aodn.org.au/download?url=http%3A%2F%2Fgeoserver-123.aodn.org.au%2Fgeoserver%2Fows%3FtypeName%3Dimos%3Amarvl3_raw_data%26SERVICE%3DWFS%26outputFormat%3Dcsv-with-metadata-header%26REQUEST%3DGetFeature%26VERSION%3D1.0.0%26CQL_FILTER%3DINTERSECTS(geom_bin%252CPOLYGON((144.8876953125%2520-21.0947265625%252C144.8876953125%2520-16.7880859375%252C155.5224609375%2520-16.7880859375%252C155.5224609375%2520-21.0947265625%252C144.8876953125%2520-21.0947265625)))&downloadFilename=MARVL3_-_Australian_shelf_salinity_data_atlas.csv&downloadToken=1474443058734"
--2016-09-21 17:33:50--  https://portal.aodn.org.au/download?url=http%3A%2F%2Fgeoserver-123.aodn.org.au%2Fgeoserver%2Fows%3FtypeName%3Dimos%3Amarvl3_raw_data%26SERVICE%3DWFS%26outputFormat%3Dcsv-with-metadata-header%26REQUEST%3DGetFeature%26VERSION%3D1.0.0%26CQL_FILTER%3DINTERSECTS(geom_bin%252CPOLYGON((144.8876953125%2520-21.0947265625%252C144.8876953125%2520-16.7880859375%252C155.5224609375%2520-16.7880859375%252C155.5224609375%2520-21.0947265625%252C144.8876953125%2520-21.0947265625)))&downloadFilename=MARVL3_-_Australian_shelf_salinity_data_atlas.csv&downloadToken=1474443058734
Resolving portal.aodn.org.au (portal.aodn.org.au)... 52.65.130.167, 52.65.218.24
Connecting to portal.aodn.org.au (portal.aodn.org.au)|52.65.130.167|:443... connected.
HTTP request sent, awaiting response... 504 GATEWAY_TIMEOUT
Retrying.

--2016-09-21 17:34:51
```

This is also bad because 5XX errors cause the nodes to be terminated and replaced, so we definitely want to resolve to minimise that unnecessary activity

**Comment by lwgordonimos** [comment] 2016-09-21 08:11
This should resolve, but will need testing tomorrow: https://github.com/aodn/chef-private/pull/2084

**Comment by lwgordonimos** [comment] 2016-09-22 03:57
Since systest has been provisioned, this has now caused the load balancer to be updated with the updated idle timeout value:
![systest_idletimeout](https://cloud.githubusercontent.com/assets/19319040/18736559/8f5bf22a-80cb-11e6-9777-8e07cc272de5.png)

@kereid this timeout related behaviour should no longer occur...

**Comment by lwgordonimos** [comment] 2016-09-22 04:08
Nope, it still happened... there must be another timeout involved, most likely on the node itself between Nginx and Tomcat... looking...

**Comment by lwgordonimos** [comment] 2016-09-22 05:14
New PR for this: https://github.com/aodn/chef-private/pull/2085

**Closed** 2016-09-22 05:26 UTC
Labels: bug
